name: deploy to aws elastic-beanstalk

on:
  push:
    branches:
      - main
env:
  MONGO_URL: ${{ vars.MONGO_URL }}

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Genrate Deployment Package
        run: zip -r nodejs-app-build.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "Test-nodejs"
          environment_name: "Test-nodejs-env"
          version_label: ${{ github.sha }}
          region: ap-southeast-2
          deployment_package: nodejs-app-build.zip
